### ISSUE TITLE
OSError: Model file not found: /home/kxniu/results/bart-large-multinews-model1/checkpoint_best.pt make: *** [bart-large.mk:98: /home/kxniu/results/bart-large-multinews-model1/test.decoded] Error 1

### ISSUE THREAD

**Issue by Sheldoer** [amazon-research/BartGraphSumm#3]
发现报这个错误 是哪个环节出问题了？

**Comment by Sheldoer** [comment]
Traceback (most recent call last):
  File "/home/kxniu/miniconda3/envs/gbart2/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/kxniu/miniconda3/envs/gbart2/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/kxniu/BartGraphSumm/src/bart_decode_parallel.py", line 41, in run
    data_name_or_path=task
  File "/home/kxniu/fairseq/fairseq/models/bart/model.py", line 104, in from_pretrained
    **kwargs,
  File "/home/kxniu/fairseq/fairseq/hub_utils.py", line 68, in from_pretrained
    arg_overrides=kwargs,
  File "/home/kxniu/fairseq/fairseq/checkpoint_utils.py", line 189, in load_model_ensemble_and_task
    raise IOError("Model file not found: {}".format(filename))
OSError: Model file not found: /home/kxniu/results/bart-large-multinews-model1/checkpoint_best.pt
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kxniu/BartGraphSumm/src/bart_decode_parallel.py", line 109, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/kxniu/BartGraphSumm/src/bart_decode_parallel.py", line 102, in main
    results = pool.map(run, args_list)
  File "/home/kxniu/miniconda3/envs/gbart2/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/kxniu/miniconda3/envs/gbart2/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
OSError: Model file not found: /home/kxniu/results/bart-large-multinews-model1/checkpoint_best.pt
make: *** [bart-large.mk:98: /home/kxniu/results/bart-large-multinews-model1/test.decoded] Error 1

**Comment by Sheldoer** [comment]
训练失败了 显存不够

**Comment by FightingEveryDay0** [comment]
hi~ I meet the same problem, did you slove it?
你好~我遇到了同样的问题，请问你是怎么解决的吗？谢谢

**Comment by lgplgplgplgp** [comment]
> 发现报这个错误是哪个阶段出问题了？



> 发现报这个错误 是哪个环节出问题了？

你好。请问你有这个模型的数据吗，可以给一下吗，谢谢

**Comment by lgplgplgplgp** [comment]
> hi~ I meet the same problem, did you slove it? 你好~我遇到了同样的问题，请问你是怎么解决的吗？谢谢

你好。请问你有这个模型的数据吗，可以给一下吗，谢谢

**Comment by lgplgplgplgp** [comment]
> 训练失败了 显存不够

你好。请问你有这个模型的数据吗，可以给一下吗，谢谢
